dist: trusty
sudo: required

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - valgrind
    - cppcheck
    - make
    - cmake


env:
  # список переменных окружения, влияющих на матрицу сборки:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    # вручную исключим ненужные элементы из матрицы сборки:
    - os:       osx
      compiler: gcc

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

script:
  # скрипт сборки и тестирования проекта:
  - gcc -std=c11 -Wall -Werror -Wpedantic -c ./src/crawlSequintally.c
  - ar r crawlSequintally.a crawlSequintally.o
  - gcc -std=c11 -Wall -Wpedantic -c -fPIC ./src/crawlParallel.c
  - gcc -shared -o crawlParallel.so crawlParallel.o
  - gcc -std=c11 -Wall -Wpedantic -c *.c
  - gcc -o dz2 *.o -fprofile-arcs -ftest-coverage -g -L. -ldynamic -lstatic -Wl,-rpath,.
  - mkdir build
  - cd build
  - cmake ..
  - cmake —build .
  - cd ..
  - ctest --output-on-failure
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind  ./dz2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck —enable=warning,performance,information ./src ./test ./include/*.h ; fi
