dist: trusty
sudo: required

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - valgrind
    - cppcheck
    - make
    - cmake


env:
  # список переменных окружения, влияющих на матрицу сборки:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    # вручную исключим ненужные элементы из матрицы сборки:
    - os:       osx
      compiler: gcc

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

script:
  # скрипт сборки и тестирования проекта:
  - gcc -std=c11 -Wall -Werror -Wpedantic -c ./crawlSequintally.c
  - ar r crawlSequintally.a crawlSequintally.o
  - gcc -std=c11 -Wall -Wpedantic -c -fPIC crawlParallel.c
  - gcc -shared -o crawlParallel.so crawlParallel.o
  - gcc -std=c11 -Wall -Wpedantic —coverage -c *.c
  - gcc -o dz2 *.o -fprofile-arcs -ftest-coverage -g -L. -ldynamic -lstatic -Wl,-rpath,.
  - ./dz2
  - gcov *.c
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lcov -t "coverage" -o coverage.info -c -d . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then genhtml -o report coverage.info ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind —leak-check=full —show-leak-kinds=all ./dz2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck —enable=warning,performance,information,style *.c *.h ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cpplint —filter=-readability,-build *.c ; fi
  - mkdir build
  - cd build
  - cmake ..
  - cmake —build .